name: Combat-TPA
version: '1.0 SNAPSHOT'
main: com.rosed.combatTPA.CombatTPA
api-version: '1.20'
commands:
  tpa:
    description: Sender /tpa <player> command that request a specific online player for a tp
  tpdeny:
    description: Receiver /tpdeny to deny current request
  tpaccept:
    description: Receiver /tpaccept to accept current request